### ISSUE TITLE
New required dependancy issue

### ISSUE THREAD

**Issue by d2kagw** [onsigntv/app-simulator#2]
Since the latest MacOS Update there is a requirement for
`pkg_resources.DistributionNotFound: The 'MarkupSafe==1.1.1' distribution was not found and is required by onsigntv-app-simulator`

but I can confirm that it is available in the environment: 
```
pip3 install MarkupSafe==1.1.1
...
Requirement already satisfied: MarkupSafe==1.1.1 in /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/MarkupSafe-1.1.1-py3.11-macosx-14-arm64.egg (1.1.1)
```

Full stack here:
```bash

Last login: Mon Sep 23 06:00:03 on ttys002
➜  ~ cd Code/onsigntv/app-simulator 
➜  app-simulator git:(main) ✗ ls -la
total 64
drwxr-xr-x  17 aaron.wallis  staff   544 23 Sep 06:00 .
drwxr-xr-x   4 aaron.wallis  staff   128 22 Oct  2023 ..
drwxr-xr-x  15 aaron.wallis  staff   480 23 Sep 06:00 .git
-rw-r--r--   1 aaron.wallis  staff    96 22 Oct  2023 .gitignore
-rw-r--r--   1 aaron.wallis  staff   796  8 Jun 16:02 .pre-commit-config.yaml
-rw-r--r--@  1 aaron.wallis  staff  1066 22 Oct  2023 LICENSE
-rw-r--r--   1 aaron.wallis  staff  1878 23 Sep 06:00 README.md
drwxr-xr-x  14 aaron.wallis  staff   448 23 Sep 06:00 app_simulator
drwxr-xr-x   6 aaron.wallis  staff   192  8 Jun 16:09 build
drwxr-xr-x   6 aaron.wallis  staff   192 23 Sep 06:01 dist
drwxr-xr-x   6 aaron.wallis  staff   192 22 Oct  2023 env
drwxr-xr-x   6 aaron.wallis  staff   192 22 Oct  2023 envn.
drwxr-xr-x   8 aaron.wallis  staff   256 23 Sep 06:01 onsigntv_app_simulator.egg-info
-rw-r--r--   1 aaron.wallis  staff   260 23 Sep 06:00 pyproject.toml
-rw-r--r--@  1 aaron.wallis  staff    30  8 Jun 16:02 requirements-dev.txt
-rw-r--r--   1 aaron.wallis  staff   156 23 Sep 06:00 requirements.txt
-rw-r--r--   1 aaron.wallis  staff  2265 23 Sep 06:00 setup.py
➜  app-simulator git:(main) ✗ python3 -m venv env           
➜  app-simulator git:(main) ✗ . env/bin/activate            
(env) ➜  app-simulator git:(main) ✗ cd ../../fur-apps/dist        
(env) ➜  dist git:(2409-quiz-updates) ✗ onsigntv-app-simulator .      
Traceback (most recent call last):
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 600, in _build_master
    ws.require(__requires__)
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 937, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 844, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (onsigntv-app-simulator 1.2.0 (/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/onsigntv_app_simulator-1.2.0-py3.11.egg), Requirement.parse('onsigntv-app-simulator==1.3.1'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/bin/onsigntv-app-simulator", line 33, in <module>
    sys.exit(load_entry_point('onsigntv-app-simulator==1.3.1', 'console_scripts', 'onsigntv-app-simulator')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/bin/onsigntv-app-simulator", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/onsigntv_app_simulator-1.2.0-py3.11.egg/app_simulator/__main__.py", line 7, in <module>
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/onsigntv_app_simulator-1.2.0-py3.11.egg/app_simulator/routes.py", line 26, in <module>
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/Jinja2-2.11.3-py3.11.egg/jinja2/loaders.py", line 233, in __init__
    from pkg_resources import DefaultProvider
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3291, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3266, in _call_aside
    f(*args, **kwargs)
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3304, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 602, in _build_master
    return cls._build_from_requirements(__requires__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 615, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 798, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 839, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'MarkupSafe==1.1.1' distribution was not found and is required by onsigntv-app-simulator
(env) ➜  dist git:(2409-quiz-updates) ✗ pip3 install 'MarkupSafe==1.1.1'
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/aiohttp_sse-2.1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/WTForms-2.3.3-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/MarkupSafe-1.1.1-py3.11-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/onsigntv_app_simulator-1.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/multidict-6.0.5-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/Pillow-9.5.0-py3.11-macosx-14.0-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/frozenlist-1.4.0-py3.11-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/multidict-6.0.4-py3.11-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/qrcode-7.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/aiosignal-1.3.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/MarkupSafe-1.1.1-py3.11-macosx-14.0-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/frozenlist-1.4.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/aiohttp-3.8.6-py3.11-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/onsigntv_app_simulator-1.3.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/Pillow-9.5.0-py3.11-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/yarl-1.9.2-py3.11-macosx-14-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/idna-3.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/feedparser-6.0.10-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/sgmllib3k-1.0.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/onsigntv_app_simulator-1.2.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/charset_normalizer-3.3.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/async_timeout-4.0.3-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/lorem-0.1.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/attrs-23.1.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/pytz-2022.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/Jinja2-2.11.3-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/yarl-1.9.4-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/aiohttp-3.8.6-py3.11-macosx-14.0-arm64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: MarkupSafe==1.1.1 in /Users/aaron.wallis/Code/onsigntv/app-simulator/env/lib/python3.11/site-packages/MarkupSafe-1.1.1-py3.11-macosx-14-arm64.egg (1.1.1)
(env) ➜  dist git:(2409-quiz-updates) ✗ 


```

I can confirm I'm using the lastest github checkout of the simulator.

**Comment by FranciscoCamerini** [comment]
Hello, @d2kagw!

I see from your stack trace that you have the `onsigntv-app-simulator` package version 1.2.0 installed in your env. Our latest version is 1.3.1.

This issue should not happen if you update the package to the latest version.
```
pip install onsigntv-app-simulator --upgrade
```
